### ISSUE TITLE
Could you give some more detail about such detection?

### ISSUE THREAD

**Issue by Summersummer3** [yhor1e/sandbox-detect-memory-leak-using-puppeteer#1]
Could you give some more detail about such detection?
I can't understand why it can leak the user is using puppeteer

**Comment by yhor1e** [comment]
@Summersummer3 

Hi. This repository is just a sandbox. 
I wanted to detect memory leaks. But the code in this repository couldn't.

**Comment by Summersummer3** [comment]
Ok I misunderstood, sorry then.
